# Generated by Django 6.0.5 on 2026-06-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Produto Físico'), ('S', 'Serviço')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='estoquefrigobar',
            name='capacidade_maxima',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='estoquefrigobar',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada (Compra/Ajuste)'), ('S', 'Saída (Perda/Ajuste)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_deposito',
            field=models.IntegerField(default=0, verbose_name='Saldo no Depósito'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_fechamento', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
