# Generated by Django 6.0.5 on 2026-06-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastro_unique_cpf_por_empresa_and_more'),
        ('estoque', '0002_produto_tipo_alter_estoquefrigobar_capacidade_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('V', 'À Vista (Caixa)'), ('P', 'A Prazo (Contas a Pagar)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel__in': ['FORNECEDOR', 'AMBOS']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada (Compra)'), ('S', 'Saída (Perda/Ajuste)')], max_length=1),
        ),
    ]
