# Generated by Django 6.0.5 on 2026-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='num_parcelas',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
    ]
