# Generated by Django 6.0.5 on 2026-05-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cadastro',
            name='unique_cpf_por_empresa',
        ),
        migrations.RemoveConstraint(
            model_name='cadastro',
            name='unique_cnpj_por_empresa',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='empresa_convenio',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel': 'CONVENIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospedes_vinculados', to='cadastros.cadastro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='passaporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='papel',
            field=models.CharField(choices=[('HOSPEDE', 'Hóspede'), ('FORNECEDOR', 'Fornecedor'), ('CONVENIO', 'Empresa/Convênio (Faturamento)'), ('AMBOS', 'Hóspede e Fornecedor')], default='HOSPEDE', max_length=15),
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='razao_social',
        ),
    ]
