# Generated by Django 6.0.5 on 2026-05-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Diária')),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Hora (Adicional ou Avulso)')),
                ('limite_adultos', models.IntegerField(default=2)),
                ('limite_criancas', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=10, verbose_name='Número/Nome do Quarto')),
                ('status', models.CharField(choices=[('DISPONIVEL', '🟢 Disponível'), ('OCUPADO', '🔴 Ocupado / Hospedado'), ('LIMPEZA', '🟡 Em Limpeza / Governança'), ('MANUTENCAO', '⚫ Manutenção')], default='DISPONIVEL', max_length=20)),
                ('andar', models.CharField(blank=True, max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.categoriaquarto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
