# Generated by Django 6.0.5 on 2026-05-30 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quarto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoriaquarto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='categoriaquarto',
            name='limite_adultos',
        ),
        migrations.RemoveField(
            model_name='categoriaquarto',
            name='limite_criancas',
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='preco_hora',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADO', 'Ocupado'), ('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=20),
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('DIARIA', 'Diária'), ('HORA', 'Hora')], default='DIARIA', max_length=10)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('hospede', models.ForeignKey(limit_choices_to={'papel': 'HOSPEDE'}, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.quarto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='andar',
        ),
    ]
