# Generated by Django 6.0.5 on 2026-06-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('hotel', '0002_alter_quarto_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoHospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='hotel.hospedagem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
