# Generated by Django 6.0.5 on 2026-06-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastro_unique_cpf_por_empresa_and_more'),
        ('hotel', '0003_consumohospedagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagem',
            name='pagador_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagas', to='cadastros.cadastro'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='valor_consumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='valor_estadia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
