# Generated by Django 6.0.5 on 2026-07-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hotel', '0004_hospedagem_pagador_final_hospedagem_valor_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedagem',
            name='quantidade_hospedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='valor_diaria_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FaixaPrecoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('qtd_hospedes', models.PositiveIntegerField()),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='hotel.categoriaquarto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'ordering': ['qtd_hospedes'],
            },
        ),
    ]
