# Generated by Django 6.0.5 on 2026-07-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_categoriaquarto_id_alter_consumohospedagem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaquarto',
            name='preco_diaria',
        ),
        migrations.RemoveField(
            model_name='categoriaquarto',
            name='preco_hora',
        ),
    ]
